//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Correios.ws.correios.rastro {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://resource.webservice.correios.com.br/", ConfigurationName="ws.correios.rastro.Service")]
    public interface Service {
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="buscaEventos", ReplyAction="http://resource.webservice.correios.com.br/Service/buscaEventosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Correios.ws.correios.rastro.buscaEventosResponse buscaEventos(Correios.ws.correios.rastro.buscaEventosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="buscaEventos", ReplyAction="http://resource.webservice.correios.com.br/Service/buscaEventosResponse")]
        System.Threading.Tasks.Task<Correios.ws.correios.rastro.buscaEventosResponse> buscaEventosAsync(Correios.ws.correios.rastro.buscaEventosRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="buscaEventosLista", ReplyAction="http://resource.webservice.correios.com.br/Service/buscaEventosListaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Correios.ws.correios.rastro.buscaEventosListaResponse buscaEventosLista(Correios.ws.correios.rastro.buscaEventosListaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="buscaEventosLista", ReplyAction="http://resource.webservice.correios.com.br/Service/buscaEventosListaResponse")]
        System.Threading.Tasks.Task<Correios.ws.correios.rastro.buscaEventosListaResponse> buscaEventosListaAsync(Correios.ws.correios.rastro.buscaEventosListaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://resource.webservice.correios.com.br/")]
    public partial class sroxml : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versaoField;
        
        private string qtdField;
        
        private string tipoPesquisaField;
        
        private string tipoResultadoField;
        
        private objeto[] objetoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
                this.RaisePropertyChanged("versao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string qtd {
            get {
                return this.qtdField;
            }
            set {
                this.qtdField = value;
                this.RaisePropertyChanged("qtd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TipoPesquisa {
            get {
                return this.tipoPesquisaField;
            }
            set {
                this.tipoPesquisaField = value;
                this.RaisePropertyChanged("TipoPesquisa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TipoResultado {
            get {
                return this.tipoResultadoField;
            }
            set {
                this.tipoResultadoField = value;
                this.RaisePropertyChanged("TipoResultado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objeto", Order=4)]
        public objeto[] objeto {
            get {
                return this.objetoField;
            }
            set {
                this.objetoField = value;
                this.RaisePropertyChanged("objeto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://resource.webservice.correios.com.br/")]
    public partial class objeto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroField;
        
        private string siglaField;
        
        private string nomeField;
        
        private string categoriaField;
        
        private string erroField;
        
        private eventos[] eventoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string sigla {
            get {
                return this.siglaField;
            }
            set {
                this.siglaField = value;
                this.RaisePropertyChanged("sigla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string erro {
            get {
                return this.erroField;
            }
            set {
                this.erroField = value;
                this.RaisePropertyChanged("erro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("evento", Order=5)]
        public eventos[] evento {
            get {
                return this.eventoField;
            }
            set {
                this.eventoField = value;
                this.RaisePropertyChanged("evento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://resource.webservice.correios.com.br/")]
    public partial class eventos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoField;
        
        private string statusField;
        
        private string dataField;
        
        private string horaField;
        
        private string descricaoField;
        
        private string detalheField;
        
        private string recebedorField;
        
        private string documentoField;
        
        private string comentarioField;
        
        private string localField;
        
        private string codigoField;
        
        private string cidadeField;
        
        private string ufField;
        
        private string stoField;
        
        private string amazoncodeField;
        
        private string amazontimezoneField;
        
        private destinos[] destinoField;
        
        private enderecoMobile enderecoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
                this.RaisePropertyChanged("hora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("descricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string detalhe {
            get {
                return this.detalheField;
            }
            set {
                this.detalheField = value;
                this.RaisePropertyChanged("detalhe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string recebedor {
            get {
                return this.recebedorField;
            }
            set {
                this.recebedorField = value;
                this.RaisePropertyChanged("recebedor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
                this.RaisePropertyChanged("documento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string comentario {
            get {
                return this.comentarioField;
            }
            set {
                this.comentarioField = value;
                this.RaisePropertyChanged("comentario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string local {
            get {
                return this.localField;
            }
            set {
                this.localField = value;
                this.RaisePropertyChanged("local");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
                this.RaisePropertyChanged("cidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
                this.RaisePropertyChanged("uf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string sto {
            get {
                return this.stoField;
            }
            set {
                this.stoField = value;
                this.RaisePropertyChanged("sto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string amazoncode {
            get {
                return this.amazoncodeField;
            }
            set {
                this.amazoncodeField = value;
                this.RaisePropertyChanged("amazoncode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string amazontimezone {
            get {
                return this.amazontimezoneField;
            }
            set {
                this.amazontimezoneField = value;
                this.RaisePropertyChanged("amazontimezone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("destino", Order=16)]
        public destinos[] destino {
            get {
                return this.destinoField;
            }
            set {
                this.destinoField = value;
                this.RaisePropertyChanged("destino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public enderecoMobile endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
                this.RaisePropertyChanged("endereco");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://resource.webservice.correios.com.br/")]
    public partial class destinos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string localField;
        
        private string codigoField;
        
        private string cidadeField;
        
        private string bairroField;
        
        private string ufField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string local {
            get {
                return this.localField;
            }
            set {
                this.localField = value;
                this.RaisePropertyChanged("local");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
                this.RaisePropertyChanged("cidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
                this.RaisePropertyChanged("bairro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
                this.RaisePropertyChanged("uf");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://resource.webservice.correios.com.br/")]
    public partial class enderecoMobile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string cepField;
        
        private string logradouroField;
        
        private string complementoField;
        
        private string numeroField;
        
        private string localidadeField;
        
        private string ufField;
        
        private string bairroField;
        
        private string latitudeField;
        
        private string longitudeField;
        
        private string celularField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
                this.RaisePropertyChanged("cep");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
                this.RaisePropertyChanged("logradouro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
                this.RaisePropertyChanged("complemento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string localidade {
            get {
                return this.localidadeField;
            }
            set {
                this.localidadeField = value;
                this.RaisePropertyChanged("localidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
                this.RaisePropertyChanged("uf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
                this.RaisePropertyChanged("bairro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
                this.RaisePropertyChanged("celular");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscaEventos", WrapperNamespace="http://resource.webservice.correios.com.br/", IsWrapped=true)]
    public partial class buscaEventosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string senha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lingua;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string objetos;
        
        public buscaEventosRequest() {
        }
        
        public buscaEventosRequest(string usuario, string senha, string tipo, string resultado, string lingua, string objetos) {
            this.usuario = usuario;
            this.senha = senha;
            this.tipo = tipo;
            this.resultado = resultado;
            this.lingua = lingua;
            this.objetos = objetos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscaEventosResponse", WrapperNamespace="http://resource.webservice.correios.com.br/", IsWrapped=true)]
    public partial class buscaEventosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Correios.ws.correios.rastro.sroxml @return;
        
        public buscaEventosResponse() {
        }
        
        public buscaEventosResponse(Correios.ws.correios.rastro.sroxml @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscaEventosLista", WrapperNamespace="http://resource.webservice.correios.com.br/", IsWrapped=true)]
    public partial class buscaEventosListaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string senha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lingua;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("objetos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] objetos;
        
        public buscaEventosListaRequest() {
        }
        
        public buscaEventosListaRequest(string usuario, string senha, string tipo, string resultado, string lingua, string[] objetos) {
            this.usuario = usuario;
            this.senha = senha;
            this.tipo = tipo;
            this.resultado = resultado;
            this.lingua = lingua;
            this.objetos = objetos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscaEventosListaResponse", WrapperNamespace="http://resource.webservice.correios.com.br/", IsWrapped=true)]
    public partial class buscaEventosListaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resource.webservice.correios.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Correios.ws.correios.rastro.sroxml @return;
        
        public buscaEventosListaResponse() {
        }
        
        public buscaEventosListaResponse(Correios.ws.correios.rastro.sroxml @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceChannel : Correios.ws.correios.rastro.Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Correios.ws.correios.rastro.Service>, Correios.ws.correios.rastro.Service {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Correios.ws.correios.rastro.buscaEventosResponse Correios.ws.correios.rastro.Service.buscaEventos(Correios.ws.correios.rastro.buscaEventosRequest request) {
            return base.Channel.buscaEventos(request);
        }
        
        public Correios.ws.correios.rastro.sroxml buscaEventos(string usuario, string senha, string tipo, string resultado, string lingua, string objetos) {
            Correios.ws.correios.rastro.buscaEventosRequest inValue = new Correios.ws.correios.rastro.buscaEventosRequest();
            inValue.usuario = usuario;
            inValue.senha = senha;
            inValue.tipo = tipo;
            inValue.resultado = resultado;
            inValue.lingua = lingua;
            inValue.objetos = objetos;
            Correios.ws.correios.rastro.buscaEventosResponse retVal = ((Correios.ws.correios.rastro.Service)(this)).buscaEventos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Correios.ws.correios.rastro.buscaEventosResponse> Correios.ws.correios.rastro.Service.buscaEventosAsync(Correios.ws.correios.rastro.buscaEventosRequest request) {
            return base.Channel.buscaEventosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Correios.ws.correios.rastro.buscaEventosResponse> buscaEventosAsync(string usuario, string senha, string tipo, string resultado, string lingua, string objetos) {
            Correios.ws.correios.rastro.buscaEventosRequest inValue = new Correios.ws.correios.rastro.buscaEventosRequest();
            inValue.usuario = usuario;
            inValue.senha = senha;
            inValue.tipo = tipo;
            inValue.resultado = resultado;
            inValue.lingua = lingua;
            inValue.objetos = objetos;
            return ((Correios.ws.correios.rastro.Service)(this)).buscaEventosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Correios.ws.correios.rastro.buscaEventosListaResponse Correios.ws.correios.rastro.Service.buscaEventosLista(Correios.ws.correios.rastro.buscaEventosListaRequest request) {
            return base.Channel.buscaEventosLista(request);
        }
        
        public Correios.ws.correios.rastro.sroxml buscaEventosLista(string usuario, string senha, string tipo, string resultado, string lingua, string[] objetos) {
            Correios.ws.correios.rastro.buscaEventosListaRequest inValue = new Correios.ws.correios.rastro.buscaEventosListaRequest();
            inValue.usuario = usuario;
            inValue.senha = senha;
            inValue.tipo = tipo;
            inValue.resultado = resultado;
            inValue.lingua = lingua;
            inValue.objetos = objetos;
            Correios.ws.correios.rastro.buscaEventosListaResponse retVal = ((Correios.ws.correios.rastro.Service)(this)).buscaEventosLista(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Correios.ws.correios.rastro.buscaEventosListaResponse> Correios.ws.correios.rastro.Service.buscaEventosListaAsync(Correios.ws.correios.rastro.buscaEventosListaRequest request) {
            return base.Channel.buscaEventosListaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Correios.ws.correios.rastro.buscaEventosListaResponse> buscaEventosListaAsync(string usuario, string senha, string tipo, string resultado, string lingua, string[] objetos) {
            Correios.ws.correios.rastro.buscaEventosListaRequest inValue = new Correios.ws.correios.rastro.buscaEventosListaRequest();
            inValue.usuario = usuario;
            inValue.senha = senha;
            inValue.tipo = tipo;
            inValue.resultado = resultado;
            inValue.lingua = lingua;
            inValue.objetos = objetos;
            return ((Correios.ws.correios.rastro.Service)(this)).buscaEventosListaAsync(inValue);
        }
    }
}
